name: Discloure day
on: workflow_dispatch
jobs:
  Developer:
    runs-on: ubuntu-latest
    steps:
      - name: Run a developer script
        run: echo Hello, Developer!
      - name: Run a multi-line developer script
        run: |
          echo this is Developer first line,
          echo this is  Developer second line.
  testers:
    runs-on: ubuntu-latest
    steps: 
      - name: Another job is tester line description
        run: echo Testing! Testing!!  
