name: hello world
on: workflow_dispatch
jobs:
  builder:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo this is first line,
          echo this is second line.
jobs:
  testers:
    runs-on:  ubuntu-latest
    steps: 
      - name: Another one line description
        run: echo Testing!
      
