name: NEW Cloud Engineer
on: workflow_dispatch
jobs:
  developer:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, developer!
      - name: Run a multi-line script
        run: |
          echo this is first line,
          echo this is second line.
  testers:
    runs-on:  ubuntu-latest
    needs: developer
    steps: 
      - name: Another one line description
        run: echo Testing!
  CloudEngineer:
    runs-on: ubuntu-latest
    needs: testers
    steps:
      - name: Learn github
        run: |
          echo keep going!!
          echo keep learning!!!
          echo keep practicing!!!
      
